version: '3'

services:
  image-reviewer:
    container_name: image_reviewer
    image: image_reviewer:latest
    ports:
      - "8501:8501"  # HTTPS/HTTP端口映射
    volumes:
      - ./certs:/app/certs  # 挂载证书目录
      - ./data:/data  # 将本地data目录挂载到容器的/data目录
    environment:
      - TZ=Asia/Shanghai
      - ROOT_DIRECTORY=/data
    restart: always

networks:
  default:
    driver: bridge

